trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Ensure Docker is available (optional, as ubuntu-latest typically has it)
    docker --version
  displayName: 'Verify Docker'

- task: SSH@0
  inputs:
    sshEndpoint: 'DigitalOceanSSH'
    runOptions: 'inline'
    inline: |
      # Navigate to the deployment directory (adjust path as needed)
      cd /var/www/backend || mkdir -p /var/www/backend && cd /var/www/backend

      # Pull the latest code from the repository
      git pull origin main

      # Stop and remove the existing container (if it exists)
      docker-compose down || true

      # Remove the last built image (optional, to free space and ensure a fresh build)
      docker rmi $(docker images -q clean-app-backend:latest) || true

      # Bring up the application using docker-compose (builds if needed)
      docker-compose up -d
  displayName: 'Deploy to DigitalOcean with Docker'