

pool:
  vmImage: ubuntu-latest
  
variables:
  - group: BackendSecrets

steps:
  - task: SSH@0
    displayName: "Gå til projektmappe"
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
        echo "Go to TaskManager folder"
        cd /var/www/backend/TaskManager || (echo "Mappe ikke fundet" && exit 1)
        /bin/pwd

  - task: SSH@0
    displayName: "Hent kode"
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
        echo "Checking path"
        cd /var/www/backend/TaskManager || (echo "Kunne ikke skifte til mappe" && exit 1)
        /bin/pwd
        echo "Henter kode"
        echo "Running git fetch:"
        git fetch 2>&1 || echo "Fetch failed"
        echo "Running git pull:"
        git pull 2>&1 || echo "Pull failed"

  - task: SSH@0
    displayName: "Opbyg og kør Docker"
    inputs:
      sshEndpoint: 'DigitalOceanSSH'
      runOptions: 'inline'
      inline: |
       echo "Go to TaskManager folder"
       cd /var/www/backend/TaskManager || (echo "Kunne ikke skifte til mappe" && exit 1)

       echo "Running docker-compose down"
       docker-compose down 2>&1 || echo "Failed to stop containers, continuing..."

       echo "Removing container taskmanager-app-1 if it exists"
       docker rm -f taskmanager-app-1 2>&1 || echo "Container taskmanager-app-1 not found or could not be removed, continuing..."

       echo "Removing image taskmanager-app if it exists"
       docker rmi taskmanager-app 2>&1 || echo "Image taskmanager-app not found or could not be removed, continuing..."

       echo "Build and run docker"
       docker-compose --env-file .env up -d --build 2>&1 || (echo "Failed to start Docker containers" && exit 1)
    