trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker --version
  displayName: 'Verify Docker'

- task: SSH@0
  inputs:
    sshEndpoint: 'DigitalOceanSSH'
    runOptions: 'inline'
    inline: |
      # Navigate to the deployment directory (adjust path as needed)
      echo "Navigating to /var/www/backend"
      cd /var/www/backend || (mkdir -p /var/www/backend && cd /var/www/backend && echo "Directory created")

      # Check current directory
      pwd

      # Pull the latest code from the repository
      echo "Pulling from Git repository"
      git pull origin main || (echo "Git pull failed, initializing repository" && git init && git remote add origin <your-repo-url> && git pull origin main)

      # Check if docker-compose.yml exists
      ls -l docker-compose.yml || echo "docker-compose.yml not found"

      # Stop and remove the existing container (if it exists)
      echo "Stopping and removing existing containers"
      docker-compose down || echo "No containers to stop or error occurred"

      # Remove the last built image (optional, to free space and ensure a fresh build)
      echo "Removing old image"
      docker rmi $(docker images -q clean-app-backend:latest) 2>/dev/null || echo "No image to remove or error occurred"

      # Bring up the application using docker-compose (builds if needed)
      echo "Starting new containers"
      docker-compose up -d || echo "Failed to start containers"

      # Verify containers are running
      echo "Checking container status"
      docker ps -a
  displayName: 'Deploy to DigitalOcean with Docker'